import type { CSSProperties } from "react";
export const pageStyles: Record<string, CSSProperties> = {
  root: {
    fontFamily: "'DM Sans', sans-serif",
    background: "#EFF8E4",
    color: "#032B14",
    minHeight: "100vh",
    overflowX: "hidden",
  },

  // NAV
  nav: {
    position: "sticky",
    top: 0,
    zIndex: 200,
    background: "rgba(3,43,20,0.94)",
    backdropFilter: "blur(18px)",
    borderBottom: "1px solid rgba(30,125,69,0.14)",
    padding: "0 3rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 68,
  },
  navLogo: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.5rem",
    fontWeight: 900,
    color: "#F5C542",
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  navDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#F5C542",
    display: "inline-block",
    flexShrink: 0,
  },
  navLinks: { display: "flex", gap: "2rem", alignItems: "center" },
  navLink: { textDecoration: "none", fontSize: 14, fontWeight: 500, color: "#5A7A67" },
  navCta: {
    background: "#032B14",
    color: "#fff",
    border: "none",
    padding: "10px 22px",
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },

  // HERO SLIDER
  heroWrap: {
    position: "relative",
    width: "100%",
    height: "min(720px, 72vh)",
    minHeight: 560,
    overflow: "hidden",
    background: "#032B14",
  },
  slide: {
    position: "absolute",
    inset: 0,
    transition: "opacity 0.9s cubic-bezier(0.4,0,0.2,1)",
  },
  slideImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center",
    display: "block",
  },
  slideOverlay: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(to top, rgba(5,20,10,0.88) 0%, rgba(5,20,10,0.45) 50%, rgba(5,20,10,0.15) 100%)",
  },
  slideContent: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: "0 6rem 4rem",
    zIndex: 10,
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "flex-end",
    gap: "3rem",
  },
  slideTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "rgba(255,255,255,0.12)",
    backdropFilter: "blur(10px)",
    border: "1px solid rgba(255,255,255,0.2)",
    padding: "5px 14px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    color: "#fff",
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    marginBottom: 18,
    width: "fit-content",
  },
  slideTagDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#F5C542",
    display: "inline-block",
    animation: "pulse 2s infinite",
  },
  slideHeadline: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "clamp(2.8rem, 5vw, 3.7rem)",
    fontWeight: 900,
    lineHeight: 1.1,
    color: "#fff",
    marginBottom: "1.25rem",
    maxWidth: 680,
    textShadow: "0 2px 24px rgba(0,0,0,0.3)",
  },
  slideAccent: {
    color: "#F5C542",
    fontStyle: "italic",
  },
  slideSub: {
    fontSize: "1.05rem",
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.75,
    maxWidth: 560,
    fontWeight: 300,
    marginBottom: "1.8rem",
  },
  slideBtns: { display: "flex", gap: 12, flexWrap: "wrap" as const },
  btnWhite: {
    background: "#fff",
    color: "#032B14",
    border: "none",
    padding: "13px 28px",
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: "0.01em",
  },
  btnGhost: {
    background: "transparent",
    color: "#fff",
    border: "2px solid rgba(255,255,255,0.5)",
    padding: "13px 28px",
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },
  statsPanel: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    alignItems: "flex-end",
  },
  statCard: {
    background: "rgba(255,255,255,0.1)",
    backdropFilter: "blur(14px)",
    border: "1px solid rgba(255,255,255,0.18)",
    borderRadius: 16,
    padding: "14px 22px",
    textAlign: "right" as const,
    minWidth: 130,
  },
  statCardNum: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "2rem",
    fontWeight: 900,
    color: "#F5C542",
    lineHeight: 1,
  },
  statCardLabel: {
    fontSize: 11,
    color: "rgba(255,255,255,0.65)",
    fontWeight: 500,
    marginTop: 4,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },
  arrow: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 20,
    width: 48,
    height: 48,
    borderRadius: "50%",
    background: "rgba(255,255,255,0.12)",
    backdropFilter: "blur(10px)",
    border: "1px solid rgba(255,255,255,0.22)",
    color: "#fff",
    fontSize: 22,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  dotsRow: {
    position: "absolute",
    bottom: 28,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 20,
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  dot: {
    height: 4,
    width: 14,
    borderRadius: 999,
    background: "rgba(255,255,255,0.4)",
    cursor: "pointer",
    transition: "width 0.35s, background 0.35s",
  },
  dotActive: {
    height: 4,
    width: 28,
    borderRadius: 999,
    background: "#F5C542",
    cursor: "pointer",
    transition: "width 0.35s, background 0.35s",
  },
  progressBar: {
    position: "absolute",
    top: 0,
    left: 0,
    height: 3,
    background: "#F5C542",
    zIndex: 30,
    transition: "width 0.1s linear",
  },

  // ABOUT
  about: { padding: "6rem 5rem", background: "#fff" },
  aboutInner: { display: "grid", gridTemplateColumns: "0.85fr 1.15fr", gap: "4rem", alignItems: "start" },
  aboutEyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#EAF7DE",
    border: "1px solid #BFE8B4",
    padding: "6px 16px 6px 10px",
    borderRadius: 999,
    marginBottom: 18,
  },
  aboutEyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#06431F",
    display: "inline-block",
    flexShrink: 0,
  },
  aboutEyebrowText: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: "#06431F",
    textTransform: "uppercase" as const,
  },
  aboutTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "2.5rem",
    fontWeight: 900,
    color: "#032B14",
    lineHeight: 1.18,
  },
  aboutTitleAccent: { color: "#06431F", fontStyle: "italic" },
  aboutAcronym: {
    marginTop: "1.5rem",
    fontSize: 13,
    fontWeight: 600,
    color: "#5A7A67",
    letterSpacing: "0.02em",
  },
  aboutBody: { display: "flex", flexDirection: "column" as const, gap: "1.4rem" },
  aboutP: {
    fontSize: 15,
    lineHeight: 1.85,
    color: "#5A7A67",
    fontWeight: 300,
  },
  aboutCallout: {
    background: "#032B14",
    borderRadius: 20,
    padding: "1.75rem 2rem",
    marginTop: "0.25rem",
  },
  aboutCalloutText: {
    fontFamily: "'Playfair Display', serif",
    fontStyle: "italic",
    fontSize: "1.15rem",
    lineHeight: 1.6,
    color: "#fff",
  },
  aboutCalloutAccent: { color: "#F5C542" },

  audience: { padding: "6rem 5rem", background: "#EFF8E4" },
  audienceHeader: { textAlign: "left" as const, marginBottom: "3.5rem", maxWidth: 520 },
  audienceLabelRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 18,
    background: "#FFF3C4",
    border: "1px solid #F0C84A",
    padding: "6px 16px 6px 10px",
    borderRadius: 999,
  },
  audienceLabelDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#06431F",
    display: "inline-block",
    flexShrink: 0,
  },
  audienceLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: "#6B4A00",
    textTransform: "uppercase" as const,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: "#06431F",
    textTransform: "uppercase" as const,
    marginBottom: 10,
  },
  sectionTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "2.4rem",
    fontWeight: 900,
    color: "#032B14",
    lineHeight: 1.2,
    marginBottom: "1rem",
  },
  audienceTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "2.75rem",
    fontWeight: 900,
    color: "#032B14",
    lineHeight: 1.12,
    marginBottom: "1.25rem",
  },
  audienceTitleAccent: {
    color: "#06431F",
    fontStyle: "italic",
  },
  audienceSubtitleRow: {
    display: "flex",
    gap: 14,
    alignItems: "flex-start",
  },
  audienceSubtitleIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    background: "#EAF7DE",
    border: "1px solid #BFE8B4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 15,
    flexShrink: 0,
    marginTop: 2,
  },
  audienceSubtitle: {
    color: "#5A7A67",
    maxWidth: 400,
    fontWeight: 300,
    fontSize: "1.08rem",
    lineHeight: 1.75,
  },
  audienceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4,1fr)",
    gap: 20,
    maxWidth: 1100,
    margin: "0 auto",
  },
  audienceCard: {
    background: "#fff",
    borderRadius: 20,
    padding: "2rem 1.5rem",
    border: "1px solid rgba(30,125,69,0.15)",
    textAlign: "center" as const,
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 14,
    transition: "transform 0.25s ease, box-shadow 0.25s ease",
  },
  audienceIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
    background: "#EAF7DE",
    border: "1px solid #BFE8B4",
  },
  audienceCheck: {
    width: 22,
    height: 22,
    borderRadius: "50%",
    background: "#06431F",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 700,
    flexShrink: 0,
  },
  audienceCardTitle: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: "1.05rem",
    color: "#032B14",
  },

  // ZETRC ACADEMY / SERVICES
  academySection: { padding: "6rem 5rem", background: "#fff" },
  academyHeader: { textAlign: "left" as const, marginTop: "4rem", marginBottom: "3rem", maxWidth: 560 },
  academyEyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#EAF7DE",
    border: "1px solid #BFE8B4",
    padding: "6px 16px 6px 10px",
    borderRadius: 999,
    marginBottom: 18,
  },
  academyEyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#06431F",
    display: "inline-block",
    flexShrink: 0,
  },
  academyEyebrowText: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: "#06431F",
    textTransform: "uppercase" as const,
  },
  academySectionTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "2.6rem",
    fontWeight: 900,
    color: "#032B14",
    lineHeight: 1.15,
    marginBottom: "0.5rem",
  },
  academyNumberBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 38,
    height: 38,
    borderRadius: 12,
    background: "#032B14",
    color: "#F5C542",
    fontFamily: "'Playfair Display', serif",
    fontWeight: 900,
    fontSize: 16,
    flexShrink: 0,
  },
  academyCard: {
    background: "#EFF8E4",
    border: "1px solid #BFE8B4",
    borderRadius: 28,
    padding: "3rem",
    display: "grid",
    gridTemplateColumns: "1.1fr 1fr",
    gap: "3rem",
    alignItems: "start",
  },
  academyCardTitleRow: { display: "flex", alignItems: "center", gap: 14, marginBottom: 14 },
  academyCardTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.6rem",
    fontWeight: 800,
    color: "#032B14",
  },
  academyCardTagline: {
    fontSize: 14.5,
    fontWeight: 600,
    color: "#06431F",
    marginBottom: 14,
  },
  academyCardDesc: {
    fontSize: 14.5,
    lineHeight: 1.8,
    color: "#5A7A67",
    fontWeight: 300,
    marginBottom: 14,
  },
  academyCardIntro: {
    fontSize: 13.5,
    fontWeight: 600,
    color: "#032B14",
    marginBottom: 14,
  },
  academyList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px 16px",
  },
  academyListItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    fontSize: 13.5,
    color: "#032B14",
    fontWeight: 500,
    lineHeight: 1.5,
  },
  academyOutro: {
    fontSize: 14,
    lineHeight: 1.8,
    color: "#5A7A67",
    fontWeight: 300,
    background: "#fff",
    border: "1px solid rgba(30,125,69,0.15)",
    borderRadius: 18,
    padding: "1.5rem",
  },
  academyOutroLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "#06431F",
    textTransform: "uppercase" as const,
    marginBottom: 8,
  },

  // ARTICLES
  articlesSection: { padding: "6rem 5rem", background: "#032B14" },
  articlesHeader: { textAlign: "left" as const, marginBottom: "2.5rem", maxWidth: 620 },
  articlesEyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#EAF7DE",
    border: "1px solid #BFE8B4",
    padding: "6px 16px 6px 10px",
    borderRadius: 999,
    marginBottom: 16,
  },
  articlesEyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#06431F",
    display: "inline-block",
    flexShrink: 0,
  },
  articlesEyebrowText: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: "#06431F",
    textTransform: "uppercase" as const,
  },
  articlesSectionTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "2.5rem",
    fontWeight: 900,
    color: "#fff",
    lineHeight: 1.15,
    marginBottom: "0.6rem",
  },
  articlesSubtitle: {
    color: "#5A7A67",
    fontWeight: 300,
    fontSize: "1.02rem",
    lineHeight: 1.7,
  },
  articlesWriteCard: {
    background: "#fff",
    border: "1px solid rgba(30,125,69,0.15)",
    borderRadius: 22,
    padding: "2rem",
    boxShadow: "0 4px 28px rgba(30,125,69,0.06)",
    marginBottom: "2.5rem",
  },
  articlesWriteTitle: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 800,
    fontSize: "1.2rem",
    color: "#032B14",
    marginBottom: 16,
  },
  articlesFormRow: { display: "grid", gridTemplateColumns: "2fr 1fr", gap: 12 },
  articlesUploadRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginTop: 14,
    marginBottom: 18,
  },
  articlesUploadLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13.5,
    fontWeight: 600,
    color: "#06431F",
    background: "#EAF7DE",
    border: "1px solid #BFE8B4",
    padding: "10px 16px",
    borderRadius: 999,
    cursor: "pointer",
  },
  articlesUploadPreview: {
    width: 44,
    height: 44,
    borderRadius: 10,
    objectFit: "cover" as const,
    border: "1px solid #BFE8B4",
  },
  articlesList: { display: "flex", flexDirection: "column" as const, gap: 24 },
  articleCard: {
    background: "#fff",
    border: "1px solid rgba(30,125,69,0.15)",
    borderRadius: 22,
    overflow: "hidden",
  },
  articleImage: {
    width: "100%",
    maxHeight: 320,
    objectFit: "cover" as const,
    display: "block",
  },
  articleBody: { padding: "1.75rem 2rem 2rem" },
  articleMeta: {
    fontSize: 12,
    fontWeight: 600,
    color: "#8FAD9A",
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    marginBottom: 8,
  },
  articleTitle: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 800,
    fontSize: "1.4rem",
    color: "#032B14",
    marginBottom: 10,
    lineHeight: 1.3,
  },
  articleContent: {
    fontSize: 14.5,
    lineHeight: 1.8,
    color: "#5A7A67",
    fontWeight: 300,
    marginBottom: "1.5rem",
  },
  reactionsRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap" as const,
    marginBottom: "1.5rem",
  },
  reactionBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#F5F9F1",
    border: "1px solid #E2EFD9",
    borderRadius: 999,
    padding: "6px 14px",
    fontSize: 13.5,
    fontWeight: 600,
    color: "#5A7A67",
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    transition: "transform 0.15s ease, background 0.15s ease",
  },
  reactionBtnActive: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#EAF7DE",
    border: "1px solid #06431F",
    borderRadius: 999,
    padding: "6px 14px",
    fontSize: 13.5,
    fontWeight: 700,
    color: "#06431F",
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    transform: "scale(1.05)",
  },
  commentsBlock: {
    borderTop: "1px solid #EAF7DE",
    paddingTop: "1.25rem",
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  commentsLabel: {
    fontSize: 13,
    fontWeight: 700,
    color: "#032B14",
  },
  commentItem: { display: "flex", gap: 12, alignItems: "flex-start" },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "#EAF7DE",
    border: "1px solid #BFE8B4",
    color: "#06431F",
    fontWeight: 700,
    fontSize: 13,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  commentName: { fontSize: 13.5, fontWeight: 700, color: "#032B14" },
  commentDate: { fontWeight: 400, color: "#8FAD9A", fontSize: 12 },
  commentText: { fontSize: 13.5, color: "#5A7A67", fontWeight: 400, marginTop: 2, lineHeight: 1.55 },
  commentForm: { display: "flex", gap: 8, flexWrap: "wrap" as const, marginTop: 4 },
  commentSubmitBtn: {
    background: "#032B14",
    color: "#fff",
    border: "none",
    padding: "0 20px",
    borderRadius: 12,
    fontSize: 13.5,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },

  cardLight: {
    background: "#fff",
    borderRadius: 20,
    padding: "2rem",
    border: "1px solid rgba(30,125,69,0.15)",
  },
  cardPale: {
    background: "#EAF7DE",
    borderRadius: 20,
    padding: "2rem",
    border: "1px solid #BFE8B4",
  },
  cardDark: {
    background: "#032B14",
    borderRadius: 20,
    padding: "2rem",
    border: "1px solid transparent",
  },
  serviceIcon: {
    width: 52,
    height: 52,
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    marginBottom: "1.25rem",
  },
  iconGreenBg: { background: "#EAF7DE", border: "1px solid #BFE8B4" },
  iconGoldBg: { background: "#FDF5E0", border: "1px solid rgba(212,168,67,0.25)" },
  iconDarkBg: { background: "rgba(255,255,255,0.1)" },
  serviceTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.2rem",
    fontWeight: 700,
    marginBottom: 10,
    color: "#032B14",
  },
  serviceTitleWhite: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.2rem",
    fontWeight: 700,
    marginBottom: 10,
    color: "#fff",
  },
  serviceDesc: { fontSize: 14, lineHeight: 1.7, fontWeight: 300, color: "#5A7A67" },
  serviceDescMuted: { fontSize: 14, lineHeight: 1.7, fontWeight: 300, color: "rgba(255,255,255,0.65)" },
  serviceList: {
    listStyle: "none",
    padding: 0,
    margin: "14px 0 0",
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  serviceListItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13.5,
    color: "#5A7A67",
    fontWeight: 400,
  },
  checkBadge: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    background: "#EAF7DE",
    border: "1px solid #BFE8B4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    color: "#06431F",
    flexShrink: 0,
  },
  academyPills: { display: "flex", flexWrap: "wrap" as const, gap: 6, margin: "14px 0 18px" },
  pillPurple: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
    background: "#FFF3C4",
    color: "#6B4A00",
    border: "1px solid #F0C84A",
  },
  academyLink: { fontSize: 14, fontWeight: 600, color: "#06431F", textDecoration: "none" },
  cardBtnGreen: {
    width: "100%",
    padding: 12,
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    border: "none",
    background: "#032B14",
    color: "#fff",
    marginTop: "1.5rem",
  },
  cardBtnPale: {
    width: "100%",
    padding: 12,
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    border: "none",
    background: "#BFE8B4",
    color: "#032B14",
    marginTop: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },

  // OUR PARTNERS
  partnersStrip: { background: "#032B14", padding: "5rem" },
  partnersHeader: { textAlign: "center" as const, marginBottom: "3rem" },
  partnersLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: "#BFE8B4",
    textTransform: "uppercase" as const,
    marginBottom: 10,
  },
  partnersTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "2.2rem",
    fontWeight: 900,
    color: "#fff",
    lineHeight: 1.2,
  },
  partnersDesc: {
    color: "rgba(255,255,255,0.6)",
    marginTop: 16,
    fontWeight: 300,
    fontSize: "1rem",
    lineHeight: 1.75,
    maxWidth: 560,
    margin: "16px auto 0",
  },
  partnersGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: 20,
    maxWidth: 1200,
    margin: "0 auto",
  },
  partnerCard: {
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 18,
    padding: "2rem 1.5rem",
    textAlign: "center" as const,
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 14,
  },
  partnerLogoCircle: {
    width: 84,
    height: 84,
    borderRadius: "50%",
    background: "#fff",
    border: "1px solid rgba(255,255,255,0.18)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 6,
  },
  partnerLogoImg: {
    width: "100%",
    height: "100%",
    objectFit: "contain" as const,
    borderRadius: "50%",
  },
  partnerName: { fontWeight: 600, color: "#fff", fontSize: 15.5 },
  partnerDesc: { fontSize: 13, color: "rgba(255,255,255,0.55)", lineHeight: 1.6, fontWeight: 300 },

  // CONTACT
  contact: { padding: "6rem 5rem", background: "#EAF7DE", borderTop: "1px solid #BFE8B4" },
  contactInner: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "5rem", alignItems: "flex-start" },
  contactDesc: { color: "#5A7A67", lineHeight: 1.8, fontWeight: 300, marginBottom: "2rem" },
  contactLinks: { display: "flex", flexDirection: "column" as const, gap: 14, marginBottom: "2rem" },
  contactLinkRow: { display: "flex", alignItems: "center", gap: 14 },
  contactLinkIcon: {
    width: 46,
    height: 46,
    borderRadius: 13,
    background: "#fff",
    border: "1px solid #BFE8B4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 19,
    flexShrink: 0,
  },
  linkLabel: { fontSize: 11, fontWeight: 700, color: "#8FAD9A", textTransform: "uppercase" as const, letterSpacing: "0.06em" },
  linkValue: { fontSize: 14, fontWeight: 600, color: "#032B14" },
  formCard: {
    background: "#fff",
    borderRadius: 24,
    border: "1px solid rgba(30,125,69,0.15)",
    padding: "2.25rem",
    boxShadow: "0 4px 32px rgba(30,125,69,0.07)",
  },
  formTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.5rem",
    fontWeight: 900,
    color: "#032B14",
    marginBottom: "1.5rem",
  },
  formRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  input: {
    padding: "12px 15px",
    borderRadius: 12,
    border: "1.5px solid #E2E8F0",
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    color: "#032B14",
    background: "#F8FAFB",
    outline: "none",
    width: "100%",
  },
  textarea: {
    padding: "12px 15px",
    borderRadius: 12,
    border: "1.5px solid #E2E8F0",
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    color: "#032B14",
    background: "#F8FAFB",
    outline: "none",
    resize: "vertical" as const,
    width: "100%",
  },
  submitBtn: {
    width: "100%",
    padding: 14,
    borderRadius: 12,
    background: "#032B14",
    color: "#fff",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    border: "none",
    marginTop: 4,
    letterSpacing: "0.02em",
  },
  btnPrimary: {
    background: "#032B14",
    color: "#fff",
    border: "none",
    padding: "14px 30px",
    borderRadius: 999,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: "0.01em",
  },

  // FOOTER
  footer: {
    background: "#032B14",
    padding: "2.5rem 5rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTop: "1px solid rgba(255,255,255,0.08)",
  },
  footerLogo: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.3rem",
    fontWeight: 900,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  footerText: { fontSize: 13, color: "rgba(255,255,255,0.4)", fontWeight: 300 },
  footerTagline: { fontSize: 12, color: "rgba(255,255,255,0.3)" },
};

export const pageRoot: CSSProperties = pageStyles.root;
